# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf
source=custom/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=hyprland/keybinds.conf

# Custom 
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf
source=quake/top.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf
# extended monitors on laptop
# Using descriptions to ensure correct placement regardless of port naming (DP-1 vs DP-5)

# Left Monitor (S2-L) - Originally DP-1
monitor = desc:SHL S2-L S2-L 20250526,1920x1080@60,0x0,1

# Center Monitor (Laptop Internal) - Originally eDP-2
monitor = desc:AU Optronics B160UAN08.1,1920x1200@144,1920x5,1

# Right Monitor (S2-R) - Originally DP-3
monitor = desc:Sensics Inc. S2-R S2-R 20250526,1920x1080@60,3840x0,1
