color0 #242120
color1 #c6685d
color2 #8ba37e
color3 #cb9168
color4 #67808a
color5 #a27886
color6 #769f93
color7 #e5dec9
color8 #36312f
color9 #db8177
color10 #9cb793
color11 #e2aa82
color12 #809ba6
color13 #bc919f
color14 #92b9ad
color15 #f4eedc

cursor                #8ba37e
cursor_text_color     #242120
background            #242120
foreground            #e5dec9
selection_foreground  #e5dec9
selection_background  #36312f
active_border_color   #8ba37e
inactive_border_color #36312f
url_color             #8ba37e

active_tab_foreground   #242120
active_tab_background   #8ba37e
inactive_tab_foreground #e5dec9
inactive_tab_background #36312f
cursor_trail_color      #e5dec9
