color0 #1d1816
color1 #c25d4e
color2 #8b9a5a
color3 #d8a657
color4 #b85a30
color5 #cc8977
color6 #c4856a
color7 #b8aca2
color8 #463b38
color9 #d47761
color10 #8b9a5a
color11 #dbb98f
color12 #c86d45
color13 #cc8977
color14 #c4856a
color15 #e6dbd3

cursor                #b85a30
cursor_text_color     #1d1816
background            #231d1b
foreground            #e6dbd3
selection_foreground  #1d1816
selection_background  #b8aca2
active_border_color   #b85a30
inactive_border_color #2e2623
url_color             #b85a30

active_tab_foreground   #1d1816
active_tab_background   #b85a30
inactive_tab_foreground #b8aca2
inactive_tab_background #2e2623
cursor_trail_color      #b8aca2
