color0 #1c1c1c
color1 #96333e
color2 #1ed759
color3 #e8e53f
color4 #aad71e
color5 #f7882d
color6 #90c722
color7 #c1c1c1
color8 #404040
color9 #1ed759
color10 #fbcb97
color11 #f3ecd4
color12 #aad71e
color13 #f7882d
color14 #90c722
color15 #f7f4ec

cursor                #aad71e
cursor_text_color     #151515
background            #151515
foreground            #f3ecd4
selection_foreground  #151515
selection_background  #aad71e
active_border_color   #aad71e
inactive_border_color #2e2e2e
url_color             #aad71e

active_tab_foreground   #151515
active_tab_background   #aad71e
inactive_tab_foreground #c1c1c1
inactive_tab_background #2e2e2e
cursor_trail_color      #c1c1c1
