color0 #2d2b33
color1 #f92672
color2 #a6e22e
color3 #f4bf75
color4 #66d9ef
color5 #ae81ff
color6 #a1efe4
color7 #e5e5d8
color8 #75715e
color9 #f92672
color10 #a6e22e
color11 #f4bf75
color12 #66d9ef
color13 #ae81ff
color14 #a1efe4
color15 #f9f8f5

cursor                #eddd8e
cursor_text_color     #2d2b33
background            #2d2b33
foreground            #e5e5d8
selection_foreground  #eddd8e
selection_background  #3e3c45
active_border_color   #eddd8e
inactive_border_color #3d3b43
url_color             #eddd8e

active_tab_foreground   #303030
active_tab_background   #eddd8e
inactive_tab_foreground #e5e5d8
inactive_tab_background #3d3b43
cursor_trail_color      #e5e5d8
