#!/usr/bin/env bash
# Splice the generated [palettes.m3] block into starship.toml between markers,
# leaving the hand-authored format section alone. Mirrors how the builtin
# starship template manages its own block.
set -euo pipefail

palette="${XDG_CACHE_HOME:-$HOME/.cache}/noctalia/starship-m3-palette.toml"
target="${STARSHIP_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/starship.toml}"

begin='# >>> NOCTALIA M3 PALETTE >>>'
end='# <<< NOCTALIA M3 PALETTE <<<'

[ -f "$palette" ] || { echo "starship-m3: no generated palette at $palette" >&2; exit 1; }
[ -f "$target" ]  || { echo "starship-m3: no starship config at $target" >&2; exit 1; }

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# Drop any previous block (markers included), keep everything else.
awk -v b="$begin" -v e="$end" '
  $0 == b { skip = 1; next }
  $0 == e { skip = 0; next }
  skip != 1 { print }
' "$target" > "$tmp"

# Trim trailing blank lines so the block always lands one blank line down.
while [ -s "$tmp" ] && [ -z "$(tail -n1 "$tmp")" ]; do
    sed -i '$d' "$tmp"
done

{
    printf '\n%s\n' "$begin"
    printf '# Generated by Noctalia from Material 3 roles - do not edit manually\n'
    cat "$palette"
    printf '%s\n' "$end"
} >> "$tmp"

# Write THROUGH the symlink (home-manager points this at the repo copy);
# a mv would replace the link with a regular file.
cat "$tmp" > "$target"
