# ~/.config/matugen/templates/hyprland/hyprlock-colors.conf
\$background = rgb(111318)
\$onBackground = rgb(e2e2e9)
\$primary = rgb(adc6ff)
\$onPrimary = rgb(102f60)
\$secondary = rgb(bfc6dc)
\$onSecondary = rgb(293041)
\$surface = rgb(111318)
\$onSurface = rgb(e2e2e9)
\$outline = rgb(8e9099)
