# Petrified Bloom (PB) - Hyprland Colors
$bg = rgb(1A1C1D)
$surface = rgb(44484A)
$primary = rgb(FC826A)
$secondary = rgb(D9AB77)
$text = rgb(EBD39D)
$muted = rgb(798581)

$active_border = rgb(FC826A) rgb(D9AB77) 45deg
$inactive_border = rgb(44484A)
