# Petrified Kaboom (PK) - Hyprland Colors
$bg = rgb(1A1C1D)
$surface = rgb(44484A)
$primary = rgb(D9AB77)
$secondary = rgb(FC826A)
$text = rgb(EBD39D)
$muted = rgb(798581)

$active_border = rgb(D9AB77) rgb(FC826A) 45deg
$inactive_border = rgb(44484A)
